@echo off

echo .
echo .
echo .............................
echo ...... LIMPIANDO CACHE ......
echo .............................
php artisan cache:clear

echo .
echo .
echo ..................................
echo ...... LIMPIANDO CACHE VISTA .....
echo ..................................
php artisan view:clear

echo .
echo .
echo ..................................
echo ...... LIMPIANDO CACHE RUTAS .....
echo ..................................
php artisan route:cache   

echo .
echo .
echo ...................................
echo ...... LIMPIANDO CACHE CONFIG .....
echo ...................................
php artisan config:cache

echo .
echo .
echo ....................................
echo ...... LIMPIANDO CACHE OPTIMIZA.....
echo ....................................
php artisan optimize

echo .
echo .
echo ...............................................
echo ............... LIMPIANDO RUTA ................
echo ...............................................
php artisan route:clear